services:
  frontend:
    build:
      context: ./Project/medisync-frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    build:
      context: ./Project/medisync-backend
    container_name: backend
    ports:
      - "8080:8080"
    restart: unless-stopped
