-- ============================================================
-- MEDISYNC SEED DATA
-- ============================================================
-- Java AlertType is the source of truth:
-- OUT_OF_STOCK, LOW_STOCK, NEAR_EXPIRY, EXPIRED,
-- RESTOCK_REQUEST, CUSTOMER_DEMAND, SPECIAL_ORDER,
-- NEW_MEDICINE, OTHER
--
-- This updates the MySQL enum to match the entity BEFORE inserts.
-- ============================================================

ALTER TABLE alerts
MODIFY COLUMN alert_type ENUM(
    'OUT_OF_STOCK',
    'LOW_STOCK',
    'NEAR_EXPIRY',
    'EXPIRED',
    'RESTOCK_REQUEST',
    'CUSTOMER_DEMAND',
    'SPECIAL_ORDER',
    'NEW_MEDICINE',
    'OTHER'
) NOT NULL;

-- Login credentials:
-- Admin:      admin1 / Password@123
-- Pharmacist: pharmacist1 / Password@123
-- SHA-256:    ff7bd97b1a7789ddd2775122fd6817f3173672da9f802ceec57f284325bf589f
--
-- MediSync dummy seed data
-- MySQL
-- Generated from the entity classes supplied in entity.zip
-- Reference date for expiry scenarios: 2026-08-09
--
-- Test accounts:
-- Admin username: admin1
-- Pharmacist username: pharmacist1
-- Password for both: Password@123
-- Password for both accounts: Password@123
-- SHA-256 hash stored in password_hash:
-- ff7bd97b1a7789ddd2775122fd6817f3173672da9f802ceec57f284325bf589f
--
-- IMPORTANT:
-- 1. Run this AFTER Hibernate has created the tables.
-- 2. This script clears existing data from these tables first.
-- 3. If your application encrypts license_number/aadhar_number before reading them,
--    replace those two dummy values with ciphertext generated by your application's
--    encryption utility.

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE sales_invoice_items;
TRUNCATE TABLE sales_invoices;
TRUNCATE TABLE inventory_losses;
TRUNCATE TABLE alerts;
TRUNCATE TABLE pharmacist_leaves;
TRUNCATE TABLE medicine_stock;
TRUNCATE TABLE medicines;
TRUNCATE TABLE customers;
TRUNCATE TABLE pharmacists;
TRUNCATE TABLE admins;

SET FOREIGN_KEY_CHECKS = 1;

-- =========================================================
-- 1. ADMINS
-- =========================================================
INSERT INTO admins
(id, username, email, password_hash, full_name, status, created_at, updated_at)
VALUES
(1, 'admin1', 'admin@medisync.com',
 'ff7bd97b1a7789ddd2775122fd6817f3173672da9f802ceec57f284325bf589f',
 'System Admin', 'ACTIVE', '2026-08-09 09:00:00', '2026-08-09 09:00:00');

-- =========================================================
-- 2. PHARMACISTS
-- =========================================================
INSERT INTO pharmacists
(id, username, email, password_hash, first_name, last_name,
 date_of_birth, license_number, aadhar_number, phone_number,
 date_of_joining, working_shift, address, employment_status,
 date_of_exit, flag_reason, created_at, updated_at)
VALUES
(1, 'pharmacist1', 'pharmacist1@medisync.com',
 'ff7bd97b1a7789ddd2775122fd6817f3173672da9f802ceec57f284325bf589f',
 'Kunal', 'Sharma',
 '1999-05-15', 'DUMMY-LIC-0001', 'DUMMY-AADHAR-0001',
 '9876543210', '2026-01-10', 'MORNING',
 'MediSync Main Pharmacy', 'ACTIVE',
 NULL, NULL, '2026-08-09 09:00:00', '2026-08-09 09:00:00'),

(2, 'pharmacist2', 'pharmacist2@medisync.com',
 'ff7bd97b1a7789ddd2775122fd6817f3173672da9f802ceec57f284325bf589f',
 'Ananya', 'Verma',
 '1998-11-20', 'DUMMY-LIC-0002', 'DUMMY-AADHAR-0002',
 '9876543211', '2026-02-01', 'EVENING',
 'MediSync Main Pharmacy', 'ACTIVE',
 NULL, NULL, '2026-08-09 09:00:00', '2026-08-09 09:00:00');

-- =========================================================
-- 3. CUSTOMERS
-- =========================================================
INSERT INTO customers
(customer_id, customer_name, contact_number, age, gender)
VALUES
(1, 'Rahul Mehta', '9000000001', 32, 'MALE'),
(2, 'Priya Singh', '9000000002', 28, 'FEMALE'),
(3, 'Amit Verma', '9000000003', 45, 'MALE'),
(4, 'Neha Kapoor', '9000000004', 36, 'FEMALE'),
(5, 'Arjun Patel', '9000000005', 51, 'MALE');

-- =========================================================
-- 4. MEDICINES
-- =========================================================
INSERT INTO medicines
(medicine_id, item_code, name, category, manufacturer, created_at)
VALUES
(1, 'MED001', 'Paracetamol 500mg', 'TABLETS', 'Sun Pharma', '2026-07-27 23:52:16'),
(2, 'MED002', 'Amoxicillin 500mg', 'CAPSULES', 'Cipla', '2026-07-27 23:52:16'),
(3, 'MED003', 'Cetirizine 10mg', 'TABLETS', 'Dr. Reddy''s', '2026-07-27 23:52:16'),
(4, 'MED004', 'Pantoprazole 40mg', 'TABLETS', 'Torrent Pharma', '2026-07-27 23:52:16'),
(5, 'MED005', 'Azithromycin 500mg', 'TABLETS', 'Cipla', '2026-07-27 23:52:16'),
(6, 'MED006', 'Dolo 650', 'TABLETS', 'Micro Labs', '2026-07-27 23:52:16'),
(7, 'MED007', 'Vitamin C Syrup', 'SYRUPS', 'Himalaya', '2026-07-27 23:52:16'),
(8, 'MED008', 'Vitamin k2', 'CAPSULES', 'Cipla', '2026-07-28 11:37:23'),
(9, 'MED009', 'Crocin 650', 'TABLETS', 'GSK', '2026-07-27 23:52:16'),
(10, 'MED010', 'Cetirizine Syrup', 'SYRUPS', 'Cipla', '2026-08-01 10:00:00'),
(11, 'MED011', 'ORS Solution', 'SYRUPS', 'Dr. Reddy''s', '2026-08-01 10:00:00'),
(12, 'MED012', 'Vitamin D3', 'CAPSULES', 'Sun Pharma', '2026-08-01 10:00:00');

-- =========================================================
-- 5. MEDICINE STOCK
--
-- Dashboard test cases:
--   stock_id 7  -> Vitamin k2 LOW STOCK (15 total)
--   stock_id 8  -> Vitamin C Syrup NEAR EXPIRY
--   stock_id 9  -> Vitamin C Syrup EXPIRED
--   stock_id 10 -> Dolo 650 OUT OF STOCK
--
-- There is deliberately only ONE low-stock medicine and ONE
-- near-expiry batch in this seed data so dashboard counts are
-- easy to verify.
-- =========================================================
INSERT INTO medicine_stock
(stock_id, batch_number, created_at, expiry_date,
 purchase_price, selling_price, stock_quantity, medicine_id)
VALUES
(1, 'P001', '2026-07-27 23:55:00', '2027-05-10',
 10.00, 15.00, 50, 1),

(2, 'A001', '2026-07-27 23:55:00', '2026-07-01',
 50.00, 75.00, 40, 2),

(3, 'A002', '2026-07-27 23:55:00', '2026-08-20',
 50.00, 75.00, 40, 2),

(4, 'C001', '2026-07-27 23:55:00', '2027-06-15',
 20.00, 30.00, 35, 3),

(5, 'P002', '2026-07-27 23:55:00', '2027-12-31',
 20.00, 30.00, 45, 4),

(6, 'AZ001', '2026-07-27 23:55:00', '2027-04-20',
 30.00, 45.00, 60, 5),

(7, 'K2001', '2026-07-28 11:37:23', '2027-07-29',
 20.00, 30.00, 15, 8),

(8, 'VCS001', '2026-08-01 10:00:00', '2026-08-25',
 25.00, 40.00, 20, 7),

(9, 'VCS002', '2026-07-20 10:00:00', '2026-07-15',
 25.00, 40.00, 25, 7),

(10, 'D65001', '2026-07-27 23:55:00', '2027-03-31',
 35.00, 50.00, 0, 6),

(11, 'CROC001', '2026-07-27 23:55:00', '2026-07-10',
 40.00, 60.00, 10, 9),

(12, 'CET001', '2026-08-01 10:00:00', '2027-02-28',
 15.00, 25.00, 50, 10),

(13, 'ORS001', '2026-08-01 10:00:00', '2027-01-31',
 12.00, 20.00, 50, 11),

(14, 'D3-001', '2026-08-01 10:00:00', '2027-11-30',
 18.00, 30.00, 50, 12);

-- =========================================================
-- 6. SALES INVOICES
-- =========================================================
INSERT INTO sales_invoices
(invoice_id, invoice_number, pharmacist_id, customer_id,
 gross_total, tax_amount, net_payable, created_at,
 discount_percentage, payment_mode)
VALUES
(1, 'INV-20260808-001', 1, 1,
 150.00, 7.50, 157.50, '2026-08-08 10:15:00',
 0.00, 'CASH'),

(2, 'INV-20260809-001', 1, 2,
 225.00, 11.25, 236.25, '2026-08-09 10:30:00',
 0.00, 'UPI'),

(3, 'INV-20260809-002', 2, 3,
 120.00, 6.00, 126.00, '2026-08-09 12:00:00',
 0.00, 'CARD'),

(4, 'INV-20260809-003', 1, 4,
 300.00, 15.00, 315.00, '2026-08-09 13:15:00',
 0.00, 'UPI');

-- =========================================================
-- 7. SALES INVOICE ITEMS
-- =========================================================
INSERT INTO sales_invoice_items
(invoice_item_id, invoice_id, medicine_id, stock_id,
 quantity, price, line_total)
VALUES
(1, 1, 1, 1, 5, 15.00, 75.00),
(2, 1, 3, 4, 2, 25.00, 50.00),
(3, 1, 4, 5, 1, 25.00, 25.00),

(4, 2, 1, 1, 5, 15.00, 75.00),
(5, 2, 2, 3, 2, 75.00, 150.00),

(6, 3, 3, 4, 2, 25.00, 50.00),
(7, 3, 8, 7, 1, 30.00, 30.00),

(8, 4, 4, 5, 4, 25.00, 100.00),
(9, 4, 5, 6, 2, 45.00, 90.00),
(10, 4, 9, 11, 1, 60.00, 60.00);

-- =========================================================
-- 8. PHARMACIST LEAVES
-- =========================================================
INSERT INTO pharmacist_leaves
(leave_id, pharmacist_id, leave_date, leave_reason, leave_type, status)
VALUES
(1, 1, '2026-08-20', 'Personal work', 'CASUAL', 'APPROVED'),
(2, 2, '2026-08-25', 'Medical appointment', 'SICK', 'PENDING');

-- =========================================================
-- 9. INVENTORY LOSSES
-- =========================================================
INSERT INTO inventory_losses
(loss_id, stock_id, medicine_id, reported_by,
 quantity, loss_type, reason, loss_amount, created_at)
VALUES
(1, 2, 2, 1,
 5, 'EXPIRED', 'Expired stock removed from inventory',
 250.00, '2026-08-09 09:30:00'),

(2, 11, 9, 1,
 2, 'EXPIRED', 'Expired Crocin batch',
 80.00, '2026-08-09 09:45:00'),

(3, 5, 4, 2,
 1, 'DAMAGED', 'Packaging damaged',
 20.00, '2026-08-08 16:00:00');

-- =========================================================
-- 10. SYSTEM / MANUAL ALERTS
--
-- These are sample alert records. Your scheduled/system alert
-- generation may create additional records, so if you run the
-- alert-generation scheduler after this seed, duplicate alerts
-- may appear depending on your AlertService logic.
-- =========================================================
INSERT INTO alerts
(alert_id, medicine_id, stock_id, requested_medicine_name,
 alert_type, description, status, created_at)
VALUES
(1, 6, 10, NULL,
 'OUT_OF_STOCK',
 'Dolo 650 is out of stock.',
 'NEW',
 '2026-08-09 09:00:00'),

(2, 8, 7, NULL,
 'LOW_STOCK',
 'Vitamin k2 stock is running low.',
 'NEW',
 '2026-08-09 09:05:00'),

(3, 7, 8, NULL,
 'NEAR_EXPIRY',
 'Vitamin C Syrup (Batch VCS001) will expire within 30 days.',
 'NEW',
 '2026-08-09 09:10:00'),

(4, 2, 2, NULL,
 'EXPIRED',
 'Amoxicillin 500mg (Batch A001) has expired.',
 'NEW',
 '2026-08-09 09:15:00'),

(5, NULL, NULL, 'Insulin Glargine',
 'NEW_MEDICINE',
 'Manual request for Insulin Glargine.',
 'PENDING',
 '2026-08-09 10:00:00'),

(6, NULL, NULL, 'Vitamin B12 Injection',
 'CUSTOMER_DEMAND',
 'Customer requested Vitamin B12 Injection, currently unavailable.',
 'PENDING',
 '2026-08-09 10:10:00');

